### ISSUE TITLE
Can't Log In on Steam Deck

### ISSUE THREAD

**Issue by OKRD342** [rtrajano/p99_login_helper#1]
Hi. I believe that I set up everything appropriately. 

When I go to launch EverQuest.bat through Steam with the appropriate launch options for MIDI and the python script, I go to log in and I get a message saying "A connection to the server could not be reached. Please check your internet connection to make sure you are online."

I am online and everything. I assume it could be something with the python script? I set it as executable.

Should I use a specific compatibility layer? I've tried "Experimental Proton" and "Proton GE-53."

**Comment by rtrajano** [comment]
Did you change the launch options to:
`flatpak run org.rncbc.qsynth & timeout 5m ./login_helper.py & %command% ; killall -9 qsynth`

Proton experimental should be fine. That error is happening because the script isn't running.

**Comment by rtrajano** [comment]
As a troubleshooting step, you can run the script in a Konsole terminal by cd-ing to it's location in the file system, then do: `./login_helper.py`

Leave that terminal window open, clear out your launch options for now, then start EQ from steam. Try to login again. If this works, then it's the launch options not correctly starting the script automatically.

**Comment by OKRD342** [comment]
I figured it out. The python script was named like "eq_login_helper.py" and the script of course calls for "login_helper.py." My bad. This is a wonderful tool.
